../rtl/alu.sv
../rtl/apb_master(try).sv
../rtl/branch_predictor.sv
../rtl/brc.sv
../rtl/CSR.sv
../rtl/ctrl_unit.sv
../rtl/EX_MEM.sv
../rtl/forward_unit.sv
../rtl/hazard_unit.sv
../rtl/ID_EX.sv
../rtl/IF_ID.sv
../rtl/IMEM.sv
../rtl/immgen.sv
../rtl/lsu4.sv
../rtl/machine_control.sv
../rtl/MEM_WB.sv
../rtl/PC.sv
../rtl/pc_ctrl_taken.sv
../rtl/pc_intr.sv
../rtl/pipelined.sv
../rtl/processor.sv
../rtl/regfile.sv
../rtl/sll.sv
../rtl/sra.sv
../rtl/srl.sv
../rtl/timer/timer.sv
../rtl/timer/clk_sel.sv
../rtl/timer/compare.sv
../rtl/timer/counter.sv
../rtl/timer/rw_control.sv
